/**
 * @fileoverview gRPC-Web generated client stub for duel.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.32.0
// source: duel.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.duel = {};
proto.duel.v1 = require('./duel_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.duel.v1.DuelServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.duel.v1.DuelServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.duel.v1.RegisterPlayerRequest,
 *   !proto.duel.v1.RegisterPlayerResponse>}
 */
const methodDescriptor_DuelService_RegisterPlayer = new grpc.web.MethodDescriptor(
  '/duel.v1.DuelService/RegisterPlayer',
  grpc.web.MethodType.UNARY,
  proto.duel.v1.RegisterPlayerRequest,
  proto.duel.v1.RegisterPlayerResponse,
  /**
   * @param {!proto.duel.v1.RegisterPlayerRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.duel.v1.RegisterPlayerResponse.deserializeBinary
);


/**
 * @param {!proto.duel.v1.RegisterPlayerRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.duel.v1.RegisterPlayerResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.duel.v1.RegisterPlayerResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.duel.v1.DuelServiceClient.prototype.registerPlayer =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/duel.v1.DuelService/RegisterPlayer',
      request,
      metadata || {},
      methodDescriptor_DuelService_RegisterPlayer,
      callback);
};


/**
 * @param {!proto.duel.v1.RegisterPlayerRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.duel.v1.RegisterPlayerResponse>}
 *     Promise that resolves to the response
 */
proto.duel.v1.DuelServicePromiseClient.prototype.registerPlayer =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/duel.v1.DuelService/RegisterPlayer',
      request,
      metadata || {},
      methodDescriptor_DuelService_RegisterPlayer);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.duel.v1.CreateMatchRequest,
 *   !proto.duel.v1.CreateMatchResponse>}
 */
const methodDescriptor_DuelService_CreateMatch = new grpc.web.MethodDescriptor(
  '/duel.v1.DuelService/CreateMatch',
  grpc.web.MethodType.UNARY,
  proto.duel.v1.CreateMatchRequest,
  proto.duel.v1.CreateMatchResponse,
  /**
   * @param {!proto.duel.v1.CreateMatchRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.duel.v1.CreateMatchResponse.deserializeBinary
);


/**
 * @param {!proto.duel.v1.CreateMatchRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.duel.v1.CreateMatchResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.duel.v1.CreateMatchResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.duel.v1.DuelServiceClient.prototype.createMatch =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/duel.v1.DuelService/CreateMatch',
      request,
      metadata || {},
      methodDescriptor_DuelService_CreateMatch,
      callback);
};


/**
 * @param {!proto.duel.v1.CreateMatchRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.duel.v1.CreateMatchResponse>}
 *     Promise that resolves to the response
 */
proto.duel.v1.DuelServicePromiseClient.prototype.createMatch =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/duel.v1.DuelService/CreateMatch',
      request,
      metadata || {},
      methodDescriptor_DuelService_CreateMatch);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.duel.v1.JoinMatchRequest,
 *   !proto.duel.v1.JoinMatchResponse>}
 */
const methodDescriptor_DuelService_JoinMatch = new grpc.web.MethodDescriptor(
  '/duel.v1.DuelService/JoinMatch',
  grpc.web.MethodType.UNARY,
  proto.duel.v1.JoinMatchRequest,
  proto.duel.v1.JoinMatchResponse,
  /**
   * @param {!proto.duel.v1.JoinMatchRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.duel.v1.JoinMatchResponse.deserializeBinary
);


/**
 * @param {!proto.duel.v1.JoinMatchRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.duel.v1.JoinMatchResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.duel.v1.JoinMatchResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.duel.v1.DuelServiceClient.prototype.joinMatch =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/duel.v1.DuelService/JoinMatch',
      request,
      metadata || {},
      methodDescriptor_DuelService_JoinMatch,
      callback);
};


/**
 * @param {!proto.duel.v1.JoinMatchRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.duel.v1.JoinMatchResponse>}
 *     Promise that resolves to the response
 */
proto.duel.v1.DuelServicePromiseClient.prototype.joinMatch =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/duel.v1.DuelService/JoinMatch',
      request,
      metadata || {},
      methodDescriptor_DuelService_JoinMatch);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.duel.v1.FindRankedMatchRequest,
 *   !proto.duel.v1.FindRankedMatchResponse>}
 */
const methodDescriptor_DuelService_FindRankedMatch = new grpc.web.MethodDescriptor(
  '/duel.v1.DuelService/FindRankedMatch',
  grpc.web.MethodType.UNARY,
  proto.duel.v1.FindRankedMatchRequest,
  proto.duel.v1.FindRankedMatchResponse,
  /**
   * @param {!proto.duel.v1.FindRankedMatchRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.duel.v1.FindRankedMatchResponse.deserializeBinary
);


/**
 * @param {!proto.duel.v1.FindRankedMatchRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.duel.v1.FindRankedMatchResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.duel.v1.FindRankedMatchResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.duel.v1.DuelServiceClient.prototype.findRankedMatch =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/duel.v1.DuelService/FindRankedMatch',
      request,
      metadata || {},
      methodDescriptor_DuelService_FindRankedMatch,
      callback);
};


/**
 * @param {!proto.duel.v1.FindRankedMatchRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.duel.v1.FindRankedMatchResponse>}
 *     Promise that resolves to the response
 */
proto.duel.v1.DuelServicePromiseClient.prototype.findRankedMatch =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/duel.v1.DuelService/FindRankedMatch',
      request,
      metadata || {},
      methodDescriptor_DuelService_FindRankedMatch);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.duel.v1.WatchMatchRequest,
 *   !proto.duel.v1.GameEvent>}
 */
const methodDescriptor_DuelService_WatchMatch = new grpc.web.MethodDescriptor(
  '/duel.v1.DuelService/WatchMatch',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.duel.v1.WatchMatchRequest,
  proto.duel.v1.GameEvent,
  /**
   * @param {!proto.duel.v1.WatchMatchRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.duel.v1.GameEvent.deserializeBinary
);


/**
 * @param {!proto.duel.v1.WatchMatchRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.duel.v1.GameEvent>}
 *     The XHR Node Readable Stream
 */
proto.duel.v1.DuelServiceClient.prototype.watchMatch =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/duel.v1.DuelService/WatchMatch',
      request,
      metadata || {},
      methodDescriptor_DuelService_WatchMatch);
};


/**
 * @param {!proto.duel.v1.WatchMatchRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.duel.v1.GameEvent>}
 *     The XHR Node Readable Stream
 */
proto.duel.v1.DuelServicePromiseClient.prototype.watchMatch =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/duel.v1.DuelService/WatchMatch',
      request,
      metadata || {},
      methodDescriptor_DuelService_WatchMatch);
};


module.exports = proto.duel.v1;

