/**
 * @fileoverview gRPC-Web generated client stub for duel.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.32.0
// source: duel.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as duel_pb from './duel_pb'; // proto import: "duel.proto"


export class DuelServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorRegisterPlayer = new grpcWeb.MethodDescriptor(
    '/duel.v1.DuelService/RegisterPlayer',
    grpcWeb.MethodType.UNARY,
    duel_pb.RegisterPlayerRequest,
    duel_pb.RegisterPlayerResponse,
    (request: duel_pb.RegisterPlayerRequest) => {
      return request.serializeBinary();
    },
    duel_pb.RegisterPlayerResponse.deserializeBinary
  );

  registerPlayer(
    request: duel_pb.RegisterPlayerRequest,
    metadata?: grpcWeb.Metadata | null): Promise<duel_pb.RegisterPlayerResponse>;

  registerPlayer(
    request: duel_pb.RegisterPlayerRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: duel_pb.RegisterPlayerResponse) => void): grpcWeb.ClientReadableStream<duel_pb.RegisterPlayerResponse>;

  registerPlayer(
    request: duel_pb.RegisterPlayerRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: duel_pb.RegisterPlayerResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/duel.v1.DuelService/RegisterPlayer',
        request,
        metadata || {},
        this.methodDescriptorRegisterPlayer,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/duel.v1.DuelService/RegisterPlayer',
    request,
    metadata || {},
    this.methodDescriptorRegisterPlayer);
  }

  methodDescriptorCreateMatch = new grpcWeb.MethodDescriptor(
    '/duel.v1.DuelService/CreateMatch',
    grpcWeb.MethodType.UNARY,
    duel_pb.CreateMatchRequest,
    duel_pb.CreateMatchResponse,
    (request: duel_pb.CreateMatchRequest) => {
      return request.serializeBinary();
    },
    duel_pb.CreateMatchResponse.deserializeBinary
  );

  createMatch(
    request: duel_pb.CreateMatchRequest,
    metadata?: grpcWeb.Metadata | null): Promise<duel_pb.CreateMatchResponse>;

  createMatch(
    request: duel_pb.CreateMatchRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: duel_pb.CreateMatchResponse) => void): grpcWeb.ClientReadableStream<duel_pb.CreateMatchResponse>;

  createMatch(
    request: duel_pb.CreateMatchRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: duel_pb.CreateMatchResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/duel.v1.DuelService/CreateMatch',
        request,
        metadata || {},
        this.methodDescriptorCreateMatch,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/duel.v1.DuelService/CreateMatch',
    request,
    metadata || {},
    this.methodDescriptorCreateMatch);
  }

  methodDescriptorJoinMatch = new grpcWeb.MethodDescriptor(
    '/duel.v1.DuelService/JoinMatch',
    grpcWeb.MethodType.UNARY,
    duel_pb.JoinMatchRequest,
    duel_pb.JoinMatchResponse,
    (request: duel_pb.JoinMatchRequest) => {
      return request.serializeBinary();
    },
    duel_pb.JoinMatchResponse.deserializeBinary
  );

  joinMatch(
    request: duel_pb.JoinMatchRequest,
    metadata?: grpcWeb.Metadata | null): Promise<duel_pb.JoinMatchResponse>;

  joinMatch(
    request: duel_pb.JoinMatchRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: duel_pb.JoinMatchResponse) => void): grpcWeb.ClientReadableStream<duel_pb.JoinMatchResponse>;

  joinMatch(
    request: duel_pb.JoinMatchRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: duel_pb.JoinMatchResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/duel.v1.DuelService/JoinMatch',
        request,
        metadata || {},
        this.methodDescriptorJoinMatch,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/duel.v1.DuelService/JoinMatch',
    request,
    metadata || {},
    this.methodDescriptorJoinMatch);
  }

  methodDescriptorFindRankedMatch = new grpcWeb.MethodDescriptor(
    '/duel.v1.DuelService/FindRankedMatch',
    grpcWeb.MethodType.UNARY,
    duel_pb.FindRankedMatchRequest,
    duel_pb.FindRankedMatchResponse,
    (request: duel_pb.FindRankedMatchRequest) => {
      return request.serializeBinary();
    },
    duel_pb.FindRankedMatchResponse.deserializeBinary
  );

  findRankedMatch(
    request: duel_pb.FindRankedMatchRequest,
    metadata?: grpcWeb.Metadata | null): Promise<duel_pb.FindRankedMatchResponse>;

  findRankedMatch(
    request: duel_pb.FindRankedMatchRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: duel_pb.FindRankedMatchResponse) => void): grpcWeb.ClientReadableStream<duel_pb.FindRankedMatchResponse>;

  findRankedMatch(
    request: duel_pb.FindRankedMatchRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: duel_pb.FindRankedMatchResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/duel.v1.DuelService/FindRankedMatch',
        request,
        metadata || {},
        this.methodDescriptorFindRankedMatch,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/duel.v1.DuelService/FindRankedMatch',
    request,
    metadata || {},
    this.methodDescriptorFindRankedMatch);
  }

  methodDescriptorWatchMatch = new grpcWeb.MethodDescriptor(
    '/duel.v1.DuelService/WatchMatch',
    grpcWeb.MethodType.SERVER_STREAMING,
    duel_pb.WatchMatchRequest,
    duel_pb.GameEvent,
    (request: duel_pb.WatchMatchRequest) => {
      return request.serializeBinary();
    },
    duel_pb.GameEvent.deserializeBinary
  );

  watchMatch(
    request: duel_pb.WatchMatchRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<duel_pb.GameEvent> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/duel.v1.DuelService/WatchMatch',
      request,
      metadata || {},
      this.methodDescriptorWatchMatch);
  }

}

